# Generated by Django 5.1.2 on 2024-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbnumber', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('publication', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('user_ID', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Catelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catelog_name', models.CharField(max_length=500)),
                ('catelog_desc', models.CharField(max_length=500)),
                ('catelog_image', models.CharField(max_length=500)),
                ('catelog_books', models.ManyToManyField(to='reactcore.books')),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(to='reactcore.books')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reactcore.students')),
            ],
        ),
    ]
