# Generated by Django 5.1.2 on 2024-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='book_chosen',
        ),
        migrations.AddField(
            model_name='students',
            name='book_chosen',
            field=models.ManyToManyField(to='reactcore.books'),
        ),
    ]
