# Generated by Django 5.1.2 on 2024-10-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='book_chosen',
        ),
    ]
