# Generated by Django 5.1.2 on 2024-10-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcore', '0002_remove_students_book_chosen_students_book_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catelog',
            name='catelog_books',
        ),
        migrations.AddField(
            model_name='catelog',
            name='catelog_books',
            field=models.ManyToManyField(to='reactcore.books'),
        ),
    ]
