# Generated by Django 5.1.2 on 2024-10-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcore', '0002_remove_students_book_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('isbnumber', models.IntegerField()),
                ('book', models.ManyToManyField(to='reactcore.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactcore.students')),
            ],
        ),
    ]
