# Generated by Django 5.1.2 on 2024-10-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcore', '0003_provide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reactcore.students'),
        ),
    ]
